# Generated by Django 2.1.5 on 2026-05-23 01:20

import uuid

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('num_participation_videos', models.IntegerField(default=20)),
                ('num_validation_videos', models.IntegerField(default=0)),
                ('num_views_by_video', models.IntegerField(default=35)),
                ('relative_background_blur_radius', models.FloatField(default=0.005, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100000.0)])),
                ('relative_gaze_size_percent', models.FloatField(default=20, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('with_audio', models.BooleanField(default=True)),
                ('stars', models.BooleanField(default=True)),
                ('random_start', models.BooleanField(default=False)),
                ('field_of_view', models.FloatField(default=40, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(150.0)])),
                ('fast_mode', models.BooleanField(default=True)),
                ('unseen_cursor', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('Standard', 'Standard'), ('FPV', 'FPV'), ('Dynamic', 'Dynamic'), ('Edge-Hover', 'Edge-Hover')], default='Standard', max_length=20, verbose_name='Mode')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('uuid', models.UUIDField(db_index=True)),
                ('activation_code', models.CharField(default='', max_length=50, verbose_name='Activation')),
                ('rotate_speed', models.FloatField(blank=True, default=None, null=True)),
                ('login_server_timestamp', models.DateTimeField(auto_now=True)),
                ('login_user_agent', models.TextField()),
                ('login_ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('login_user_agent_parsed', django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False)),
                ('login_client_timestamp', models.DateTimeField(null=True)),
                ('login_client_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('react_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('questions_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('completed', models.BooleanField(default=False)),
                ('admin_mode', models.BooleanField(default=False)),
                ('experiment', models.ForeignKey(on_delete=models.deletion.CASCADE, to='salimouse.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('is_validation', models.BooleanField(default=False)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('server_timestamp', models.DateTimeField(null=True)),
                ('client_timestamp_start', models.DateTimeField(null=True)),
                ('client_timestamp_finish', models.DateTimeField(null=True)),
                ('data_gazes', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('data_fps', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('video_score', models.IntegerField(default=0)),
                ('participation', models.ForeignKey(on_delete=models.deletion.CASCADE, to='salimouse.Participation')),
                ('video', models.ForeignKey(on_delete=models.deletion.CASCADE, to='salimouse.Video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoViewChunkData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_server', models.DateTimeField()),
                ('timestamp_client', models.DateTimeField()),
                ('client_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('participation', models.ForeignKey(on_delete=models.deletion.CASCADE, to='salimouse.Participation')),
                ('video', models.ForeignKey(on_delete=models.deletion.CASCADE, to='salimouse.Video')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='videos',
            field=models.ManyToManyField(to='salimouse.Video'),
        ),
    ]
