events {
    worker_connections 2048;
}

#error_log /var/log/nginx/error.log warn;

http {
    #access_log  /Library/Logs/nginx/access.log;
    include /etc/nginx/mime.types;

    keepalive_timeout  600;
    client_max_body_size 2000m;

    sendfile on;
    tcp_nopush on; 
    tcp_nodelay on;

    proxy_connect_timeout 600;
    proxy_send_timeout 600;
    proxy_read_timeout 600;


    gzip on;
    gzip_disable "msie6";

    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    server {
        # if no Host match, close the connection to prevent host spoofing
        listen 80 default_server;
        return 444;
    }

    server {
        listen       0.0.0.0:80;
        server_name  example.com;
        charset utf-8;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        location / {
            add_header 'Cache-Control' 'must-revalidate';
            proxy_pass http://web/;
        }

        location /static/experiment_video/ {
            alias /home/web/experiment_video/;
            try_files $uri =404;
        }

        location /static/ {
            alias /home/web/static/;
            try_files $uri =404;
        }

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }
    }

    server {
        listen 443 ssl;
        server_name  example.com;
        charset utf-8;
        
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        location / {
            add_header 'Cache-Control' 'must-revalidate';
            proxy_pass http://web/;
        }

        location /static/experiment_video/ {
            alias /home/web/experiment_video/;
            try_files $uri =404;
        }

        location /static/ {
            alias /home/web/static/;
            try_files $uri =404;
        }
        
        ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    }

}

